name: hotel_booking
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  figma_squircle: ^0.5.3
  
  get: ^4.6.1
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  http: ^0.13.5
  dio: ^4.0.0
  flutter_native_splash: ^2.2.18
  shared_preferences: ^2.0.20
  google_sign_in: ^6.0.2
  cloudinary_public: ^0.20.0
  image_picker: ^0.8.4+4
  path_provider: ^2.0.8
  readmore: ^2.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans/static/OpenSans/OpenSans-Regular.ttf


    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf

    - family: ShantellSans
      fonts:
        - asset: fonts/ShantellSans/static/ShantellSans-Italic.ttf


flutter_native_splash:
  background_image: "assets/splash.png"