name: hotel_booking
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  get: ^4.6.1
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  http: ^0.13.5

  dio: ^4.0.0
  google_maps_flutter: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appLogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf

    - family: ShantellSans
      fonts:
        - asset: fonts/ShantellSans/static/ShantellSans-Italic.ttf
    
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans/static/OpenSans/OpenSans-Regular.ttf
